# Generated by Django 5.2.1 on 2025-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=8192)),
                ('author', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('cover', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=64)),
                ('read', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usermanager',
            name='avatar',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='introduction',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='photo',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='signature',
            field=models.CharField(default='', max_length=128),
        ),
    ]
