# Generated by Django 5.2.1 on 2025-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_articles_usermanager_avatar_usermanager_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='nickname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='work',
            field=models.CharField(default='', max_length=128),
        ),
    ]
