# Generated by Django 4.2.23 on 2025-07-03 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usermanager_nickname_usermanager_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='time',
        ),
        migrations.AddField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='state',
            field=models.CharField(choices=[('已发布', '已发布'), ('草稿', '草稿')], default='草稿', max_length=20),
        ),
        migrations.AddField(
            model_name='articles',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='myapp.usermanager'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
