# Generated by Django 4.2.23 on 2025-07-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_articles_comment_remove_articles_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
